# To run local backstage instance with docker services,
# run:
# 1. `docker compose -f docker-compose.deps.yml up --wait`
# 2. `BACKSTAGE_ENV=docker yarn dev`
backend:
  database:
    client: pg
    connection:
      host: localhost
      port: 5432
      user: postgres
      password: postgres
  cache:
    store: redis
    connection: redis://localhost:6379

search:
  elasticsearch:
    provider: opensearch
    node: 'http://localhost:9200'
    auth:
      username: admin
      password: admin
